### ISSUE TITLE
Atom for SASS should have node-sass as peer-dependency, or dependency

### ISSUE THREAD

**Issue by Hartorn** [thc-tools/webpack-laboratory#95]
**Describe the bug**

No warning that node-sass is needed
**What is the current behavior?**
When lauching build, it says to install node-sass
**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

Either dependency should be installed, or at least a peer dependency

Node.js version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by c3dr0x** [comment]
I think it can be a dependency as it is required only by the scss quark
